### ISSUE TITLE
Different puzzle already solved.

### ISSUE THREAD

**Issue by znjp** [znjp/shadowCaster-server#4]
I solved SC5, then changed (via admin panel) to SC6, and it said that one had already been solved too. I think this is because web.py's session cookie knows nothing about which shadow caster it is, nor does the database know. This is something that should be probably be reset when we change the SC in the admin panel.
BUT, a few players last time said they experienced the same thing. I wonder if web.py's session cookie code isn't as unique as it should be. Let's look into that, and see if there's some unique identifier we can see the sessions with.

**Comment by meinfr13nd** [comment]
I set it up so that when the server is restarted, it resets everything

**Comment by znjp** [comment]
Well, hold on. The reason it was stateful was in case the server had to reboot during the game, not everyone's progress was lost.
The correct behavior is probably to reset state when the SC# changes.

**Comment by meinfr13nd** [comment]
Had an idea to make it stateful by adding boolean values to the database for each shadow caster

**Comment by meinfr13nd** [comment]
The shadowcasters are now fully independent
